version: "3.9"
 
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
  flask:
    build: .
    container_name: flask-app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
     MYSQL_HOST: db
     MYSQL_PORT: 3306
     MYSQL_DB: flaskdb
     MYSQL_USER: flaskuser
     MYSQL_PASSWORD: flaskpass
     SECRET_KEY: "this-is-my-secret-key"
 
volumes:
  mysql_data:
 