apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask
type: Opaque
stringData:
  MYSQL_HOST: "flask-db.cz6uiq4kk6wc.us-east-2.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "StrongPass123!"
  MYSQL_DB: "flaskdb"